### ISSUE TITLE
RSA Authentication

### ISSUE THREAD

**Issue by trasherdk** [brechtpm/gulp-deploy-ssh#1]
@brechtpm 
I'm missing the private key authentication, documented in the gulp-ssh package,
or am I misunderstanding something.

**Comment by brechtcs** [comment]
If you're using private key authentication, just using `gulp-ssh` directly should work for you. This plugin is a thin layer on top of that plugin that covers the narrow use case were you don't use RSA, but want to prompt for a username and password instead.

I should probably clarify this in the README if it's confusing people.

**Comment by brechtcs** [comment]
Closed by https://github.com/brechtpm/gulp-deploy-ssh/pull/2
